# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-02 23:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=16)),
                ('user_email', models.CharField(max_length=160)),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='times',
            unique_together=set([('start_time', 'end_time', 'event_id')]),
        ),
    ]
