# Generated by Django 2.0.4 on 2018-04-25 01:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainview.categories')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=160)),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
                ('zipcode', models.CharField(default=16802, max_length=10)),
                ('user_email', models.CharField(max_length=160)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('upvote_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('planned_event', models.BooleanField()),
                ('categories', models.ManyToManyField(to='mainview.categories')),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.event')),
            ],
            options={
                'verbose_name_plural': 'upvotes',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(to='mainview.file'),
        ),
    ]
