# Generated by Django 2.0.4 on 2018-04-25 04:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='images',
            field=models.ManyToManyField(blank=True, to='mainview.file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='upvote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
