# Generated by Django 2.0.4 on 2018-04-26 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0002_auto_20180426_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comment', to='mainview.event')),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.RemoveField(
            model_name='comments',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
