# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0002_auto_20180403_0005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='times',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='times',
            name='event_id',
        ),
        migrations.DeleteModel(
            name='times',
        ),
    ]
