# Generated by Django 2.0.4 on 2018-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0002_auto_20180425_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='planned_event',
            field=models.BooleanField(default=False),
        ),
    ]
