# Generated by Django 2.0.4 on 2018-04-26 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0003_auto_20180426_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='long',
            new_name='lng',
        ),
        migrations.AlterField(
            model_name='file',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='mainview.event'),
        ),
    ]
