# Generated by Django 2.0.4 on 2018-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0004_auto_20180426_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='upvote_count',
            field=models.IntegerField(auto_created=0, default=0),
        ),
    ]
