# Generated by Django 2.0.4 on 2018-04-10 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0004_images_users_zip_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.event')),
            ],
        ),
        migrations.CreateModel(
            name='event_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.categories')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.event')),
            ],
        ),
        migrations.CreateModel(
            name='times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.event')),
            ],
        ),
        migrations.CreateModel(
            name='upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='times',
            unique_together={('start_time', 'end_time', 'event_id')},
        ),
    ]
