# Generated by Django 2.0.4 on 2018-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0005_auto_20180426_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
