# Generated by Django 2.0.4 on 2018-04-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0005_auto_20180410_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
