# Generated by Django 2.0.4 on 2018-04-26 08:20

from django.db import migrations, models
import mainview.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0006_auto_20180426_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=mainview.models.get_file_path),
        ),
    ]
