# Generated by Django 2.0.4 on 2018-04-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0006_event_upvote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeName', to='mainview.event'),
        ),
    ]
