# Generated by Django 2.0.4 on 2018-04-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0012_auto_20180415_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='name',
            new_name='title',
        ),
    ]
