# Generated by Django 2.0.4 on 2018-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0013_auto_20180415_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
