# Generated by Django 2.0.4 on 2018-04-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0014_auto_20180418_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
