# Generated by Django 2.0.4 on 2018-04-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0015_users_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
